### ISSUE TITLE
attack cast delay crash

### ISSUE THREAD

**Issue by Luquini** [hrt/Lmeme#1]
after some time ingame i get a crash with this error
KeyError: 'mAttackDelayCastOffsetPercent'

Any tips to solve?

**Comment by hrt** [comment]
Known issue that I won't be fixing.
It's specfic to certain champions https://github.com/hrt/Lmeme/blob/master/champion_stats.py#L28

**Comment by yinee-c** [comment]
i have that error everytime i try to hold space, even on jinx

**Comment by hrt** [comment]
Jinx is an example of a champion this wont work with.

**Comment by hrt** [comment]
I've made a temporary and inefficient fix for these champions: https://github.com/hrt/Lmeme/commit/bd1c4864a06df4a0f02a90755ff9450bbda81bd2

**Comment by hrt** [comment]
And another attempted improvement: d01716f
