### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by JJ34D** [hrt/Lmeme#2]
Limited to 2.5 attack speed unless manually changing "attack_speed" = AS in orbwalker.py. Sometimes mouse teleports.

**Comment by hrt** [comment]
I haven't experienced this.

**Comment by JJ34D** [comment]
Which part haven't you experienced, the mouse teleport might be person specific but the kiting calculations will always only kite at 2.5 AS at least on my end.

**Comment by hrt** [comment]
Yes the 2.5 attack speed cap was intentional. Didn't get around to figuring out how to get the attack speed cap.

**Comment by hrt** [comment]
8e2604a

attack speed cap adjusted to 90 if hail of blade or lethal tempo is active

**Comment by hrt** [comment]
Try playing with lowest settings and vsync on/off for random teleport problems

**Comment by JJ34D** [comment]
Ah okay yea I have seen that this has been recently added. Unable to test due to new S12 offsets I think.

**Comment by JJ34D** [comment]
![image](https://user-images.githubusercontent.com/86395137/142308272-bb262817-5d7c-466a-bc18-dbfb2abf5b65.png)

**Comment by hrt** [comment]
I updated the offsets a minute ago.

**Comment by JJ34D** [comment]
https://streamable.com/xzg3df

Doesn't attack on my end for some reason.

**Comment by hrt** [comment]
Did you start the script after you added the dummy? Otherwise I'd have expected the script to crash or work.

**Comment by JJ34D** [comment]
Ah yea you're right. Mouse still seems to teleport now and then even at lowest settings vsync, I get around 500 fps lowest settings btw. Sorry if I am coming off as pushy I'm just interested in your project.

**Comment by JJ34D** [comment]
All issues patched I appreciate your assistance.
