### ISSUE TITLE
How can I lower the click rate ?

### ISSUE THREAD

**Issue by StrikerOnLine** [hrt/Lmeme#7]
I think that the clicks per second are too much, could you allow me to lower the intensity ? and how do I do it ?

**Comment by xTheodor** [comment]
You can tinker with timer [here](https://github.com/hrt/Lmeme/blob/f060e28aae4250b04fe4a34335dbf31ffabaf7e7/main.py#L35)

**Comment by JJ34D** [comment]
Change sleep timer on main
